#!/usr/bin/env python3
"""Generate / verify CORPUS-MANIFEST.yaml from the corpus. (Decision T3.5)

The machine-readable manifest was hand-maintained, which is exactly how it drifts from
reality. This makes it a *generated* artifact: the index is derived from the corpus, and a
stale/hand-edited manifest becomes a build/test failure. Represent, then enforce
(CORE-INVARIANT 10); moves manifest integrity from asserted toward enforced.

Zero-dependency by design (like the validator). Reuses the validator's ONE YAML reader
(load_doc) rather than adding a second parser, to avoid parser-differential risk (KF-03).

Usage:
  python3 TOOLS/lore_build_manifest.py            # --write (default): regenerate the manifest
  python3 TOOLS/lore_build_manifest.py --check     # exit 1 if the on-disk manifest is stale

Author-owned header fields (corpus, version, status, description) are PRESERVED from the
existing manifest; only the derived index (schemas, registries, tools) and generated_at are
regenerated. --check ignores generated_at (it is expected to vary).
"""
import os
import sys
import argparse
from datetime import datetime, timezone

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
sys.path.insert(0, os.path.dirname(__file__))
from lore_validate import load_doc  # single source of truth for parsing (KF-03)

MANIFEST = os.path.join(REPO, 'CORPUS-MANIFEST.yaml')
HEADER_FIELDS = ['corpus', 'version', 'status', 'description']
HEADER_DEFAULTS = {
    'corpus': 'LORE',
    'version': 'v0.5.0-phase1-scaffold',
    'status': 'candidate',
    'description': 'Phase-1 bootstrap scaffold for LORE Corpus Workbench.',
}


def _rel(path):
    return os.path.relpath(path, REPO).replace(os.sep, '/')


def _list(dirpath, keep):
    if not os.path.isdir(dirpath):
        return []
    return [os.path.join(dirpath, f) for f in os.listdir(dirpath)
            if os.path.isfile(os.path.join(dirpath, f)) and keep(f)]


def derive_index():
    """Derive the mechanical index (schemas, registries, tools) from disk."""
    schemas = sorted(_rel(p) for p in _list(
        os.path.join(REPO, 'SCHEMAS'), lambda f: f.endswith('.schema.json')))
    registries = sorted(_rel(p) for p in _list(
        os.path.join(REPO, 'REGISTRIES'), lambda f: not f.upper().startswith('README')))
    tools = _list(os.path.join(REPO, 'TOOLS'), lambda f: f.endswith('.py'))
    tools += _list(os.path.join(REPO, 'TOOLS', 'hooks'),
                   lambda f: not f.upper().startswith('README'))
    tools = sorted(_rel(p) for p in tools)
    return {'schemas': schemas, 'registries': registries, 'tools': tools}


def read_header():
    hdr = dict(HEADER_DEFAULTS)
    if os.path.exists(MANIFEST):
        doc = load_doc(MANIFEST)
        for k in HEADER_FIELDS:
            if k in doc:
                hdr[k] = doc[k]
    return hdr


def render(hdr, index, timestamp):
    lines = [
        '# GENERATED by TOOLS/lore_build_manifest.py - do NOT hand-edit.',
        '# Regenerate: python3 TOOLS/lore_build_manifest.py --write    Enforce staleness: --check',
        'corpus: ' + str(hdr['corpus']),
        'version: ' + str(hdr['version']),
        'status: ' + str(hdr['status']),
        'description: "' + str(hdr['description']) + '"',
        'generated_at: "' + timestamp + '"',
        'generator: "TOOLS/lore_build_manifest.py"',
    ]
    for name in ('schemas', 'registries', 'tools'):
        lines.append('')
        lines.append(name + ':')
        for item in index[name]:
            lines.append('  - ' + item)
    return '\n'.join(lines) + '\n'


def cmd_write():
    hdr = read_header()
    index = derive_index()
    ts = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
    with open(MANIFEST, 'w', encoding='utf-8') as f:
        f.write(render(hdr, index, ts))
    print('[WROTE] CORPUS-MANIFEST.yaml  (%d schemas, %d registries, %d tools)'
          % (len(index['schemas']), len(index['registries']), len(index['tools'])))
    return 0


def cmd_check():
    if not os.path.exists(MANIFEST):
        print('[STALE] CORPUS-MANIFEST.yaml is missing - run --write.')
        return 1
    on_disk = load_doc(MANIFEST)
    fresh = derive_index()
    drift = []
    for name in ('schemas', 'registries', 'tools'):
        have = list(on_disk.get(name, []))
        want = fresh[name]
        if have != want:
            drift.append((name, sorted(set(want) - set(have)), sorted(set(have) - set(want))))
    if drift:
        print('[STALE] CORPUS-MANIFEST.yaml does not match the corpus. Run --write.')
        for name, missing, extra in drift:
            if missing:
                print('  %s: on disk but not in manifest: %s' % (name, ', '.join(missing)))
            if extra:
                print('  %s: in manifest but not on disk: %s' % (name, ', '.join(extra)))
        return 1
    print('[OK] CORPUS-MANIFEST.yaml matches the corpus (schemas/registries/tools).')
    return 0


def main():
    ap = argparse.ArgumentParser(description='Generate/verify CORPUS-MANIFEST.yaml (T3.5).')
    ap.add_argument('--check', action='store_true',
                    help='Exit non-zero if the on-disk manifest is stale (for CI/build).')
    args = ap.parse_args()
    return cmd_check() if args.check else cmd_write()


if __name__ == '__main__':
    sys.exit(main())
